### ISSUE TITLE
[FEAT] - Can I add Another Branch For WEB Projects

### ISSUE THREAD

**Issue by AFZL210** [prathamesh-borse/Hacktoberfest_2021#77]
### What feature would you like to see?

Create New Branch Named "WEB" and add different Web Projects like landing pages , side bars and other web projects

**Comment by prathamesh-borse** [comment]
> Hi please assign this issue to me I want to contribute on this repository

OK, Go ahead I am Assigning This Issue to You

**Comment by gulshanjakhon** [comment]
please check my PR Web Project added #78 
in this PR i added a E-commerce Website(Named as i.e. ShopKaro ) which was made using Html css javascript

**Comment by prathamesh-borse** [comment]
Reopened this issue for @AFZL210 because he also wants to add his Projects to this Repository.
